export const FILE = { PENDING: 0, LOADING: 1, LOADED: 2, FAILED: 3, PROCESSING: 4, COMPLETE: 5, DESTROYED: 6 };
export const LOADER = { PENDING: 0, LOADING: 1, PROCESSING: 2, COMPLETE: 3, FAILED: 4, DESTROYED: 5 };
